Web/Web/Controllers/DataController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.Models;

namespace Web.Controllers
{
    public class DataController : Controller
    {
        BangDiemEntities db = new BangDiemEntities();
        // GET: Data
        public ActionResult ListFolder()
        {
            //kiểm tra đăng nhập
            if (Session["TenTaiKhoan"] == null || Session["Admin"].ToString() == "")
            {
                return RedirectToAction("Index", "Login");
            }
            return View(db.BANGDIEMs.ToList());
        }
        public ViewResult FolderTheoLanHoc(int Id_Lan = 1)
        {

            LANHOC listFolder = db.LANHOCs.SingleOrDefault(n => n.Id == Id_Lan);
            if (listFolder == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            List<BANGDIEM> lstBangDiem = db.BANGDIEMs.Where(n => n.Id_LanHoc == Id_Lan).OrderBy(n => n.UrlFile).ToList();
            if (lstBangDiem.Count == 0)
            {
                ViewBag.lstBangDiem = "Không có folder nào thuộc loại này";
            }
            Session["namePage"] = listFolder.TenLan;
            ViewBag.lstBangDiem = db.BANGDIEMs.ToList();
            return View(lstBangDiem);
        }
        public ActionResult ListFile(int id = 1)
        {
            //kiểm tra đăng nhập
            if (Session["TenTaiKhoan"] == null || Session["Admin"].ToString() == "")
            {
                return RedirectToAction("Index", "Login");
            }

            BANGDIEM listFile = db.BANGDIEMs.SingleOrDefault(n => n.Id == id);
            string[] url = listFile.UrlFile.Split('\\');
            Session["Url"] = url[url.Length - 1];
            if (listFile == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            if (!System.IO.Directory.Exists(listFile.UrlFile))
            {
                return RedirectToAction("ListFolder", "Data");
            }
            ViewBag.File = Directory.GetFiles(@listFile.UrlFile);
            return View(listFile);
        }
    }
}

Web/Web/Controllers/OCRController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IronOcr;
namespace Web.Controllers
{
    public class OCRController : Controller
    {
        // GET: OCR
        public ActionResult OCRFile(string filename)
        {
            if (Session["TenTaiKhoan"] == null || Session["Admin"].ToString() == "")
            {
                return RedirectToAction("Index", "Login");
            }
            ViewBag.pdf = filename;
            ViewBag.File = new IronTesseract().Read(@filename).Text;

            return View();
        }
    }
}

Web/Web/Views/Data/FolderTheoLanHoc.cshtml
@model List<BANGDIEM>
@using Web.Models
@{
    ViewBag.Title = "FolderTheoLanHoc";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{
    BangDiemEntities db = new BangDiemEntities();
    <div class="table-agile-info">
        <div class="panel panel-default">
            <div class="panel-heading">
                @Session["namePage"]
            </div>
            <div>
                <table class="table" ui-jq="footable">
                    <thead>
                        <tr>
                            <th data-breakpoints="xs">ID</th>
                            <th>Name Folder</th>

                        </tr>
                    </thead>
                    <tbody>
                        @{
                            foreach (var item in Model)
                            {
                                string[] arr = @item.UrlFile.Split('\\');
                                <tr data-expanded="true">
                                    <td><a href="@Url.Action("ListFile", "Data", new {@id=item.Id})">@item.Id</a></td>
                                    <td><a href="@Url.Action("ListFile", "Data", new {@id=item.Id})">@arr[@arr.Length - 1]</a></td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
}

Web/Web/Views/Data/ListFile.cshtml
@model Web.Models.BANGDIEM
@{
    ViewData["Title"] = "ListFile";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="table-agile-info">
    <div class="panel panel-default">
        <div class="panel-heading">
            @Session["Url"]
        </div>
        <div>
            <table class="table" ui-jq="footable">
                <p> @ViewBag.TestFile</p>
                <thead>
                    <tr>
                        <th data-breakpoints="xs">ID</th>
                        <th>Name Folder</th>

                    </tr>
                </thead>
                <tbody>
                    @{
                        int i = 0;
                        foreach (var item in ViewBag.File)
                        {
                            i++;
                            string[] arr = @item.Split('\\');
                            <tr data-expanded="true">
                                <td><a href="@Url.Action("OCRFile", "OCR", new {@filename= item})" target="_blank">@i</a></td>
                                <td><a href="C:\\Users\\Admin\\Documents\\DO THI HIEN.pdf" target="_blank">@arr[@arr.Length - 1]</a></td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

Web/Web/Views/Data/ListFolder.cshtml
@model List<BANGDIEM>
@using Web.Models
@{
    ViewBag.Title = "ListFolder";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{
    BangDiemEntities db = new BangDiemEntities();
    <div class="table-agile-info">
        <div class="panel panel-default">
            <div class="panel-heading">
                All Folder
            </div>
            <div>
                <table class="table" ui-jq="footable">
                <p> @ViewBag.TestFile</p>
                    <thead>
                        <tr>
                            <th data-breakpoints="xs">ID</th>
                            <th>Name Folder</th>

                        </tr>
                    </thead>
                    <tbody>
                        @{
                            foreach (var item in Model)
                            {
                                string[] arr = @item.UrlFile.Split('\\');
                                <tr data-expanded="true">
                                    <td><a href="@Url.Action("ListFile", "Data", new {@id=item.Id})">@item.Id</a></td>
                                    <td><a href="@Url.Action("ListFile", "Data", new {@id=item.Id})">@arr[@arr.Length-1]</a></td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
}